export default {
  gtelPortal: {
    companyName: 'GTEL',
    companyFullname: 'Tổng công ty công nghệ - viễn thông toàn cầu',
    introDescription1: 'Cuộc cách mạng 4.0 mở ra kỷ nguyên số với sự chuyển đổi toàn diện về đời sống xã hội, mở ra nhiều cơ hội, song cũng đặt ra không ít thách thức đối với vấn đề an ninh truyền thống và phi truyền thống, Bộ Công an xác định để thực hiện thắng lợi nhiệm vụ xây dựng lực lượng Công an nhân dân chính quy – tinh nhuệ, hiện đại thì công nghiệp An ninh là một bộ phận quan trọng trong thực lực và tiềm lực của lực lượng CAND, vừa phục vụ công tác chiến đấu và xây dựng lực lượng vừa phục vụ phát triển kinh tế xã hội.',
    introDescription2: 'Là Tổng công ty duy nhất của ngành Công an có vai trò trực tiếp phục vụ quốc phòng – an ninh, tiên phong trong lĩnh vực công nghệ - viễn thông, GTEL đảm trách một sứ mệnh đặc biệt. Với sứ mệnh đó, GTEL luôn xác định nhiệm vụ trọng tâm là viễn thông, tự động hóa, đồng thời, dần chuyển mình sang nhiều lĩnh vực công nghệ cao, thực hiện Đề án 06 và Chương trình Chuyển đổi số Quốc gia của Chính phủ, hướng đến mục tiêu vừa phục vụ phát triển công nghiệp an ninh, công nghiệp an ninh mạng vừa phát triển kinh tế, đóng góp mạnh mẽ vào xây dựng lực lượng Công an, hòa mình vào nền công nghiệp hiện đại của quốc gia, trở thành doanh nghiệp có tầm ảnh hưởng quốc tế.',
    introBlock1_label: 'Tầm nhìn',
    introBlock1_content: 'Trở thành Tập đoàn Công nghệ - Viễn thông mạnh, hiện đại, tiên tiến trong nước và thế giới và là doanh nghiệp trực tiếp phục vụ quốc phòng, an ninh hàng đầu Bộ Công an, phục vụ đắc lực công tác chiến đấu và sẵn sàng chiến đấu của lực lượng CAND.',
    introBlock2_label: 'Sứ mệnh',
    introBlock2_content: 'Tiên phong trong việc kiến tạo xã hội số, xây dựng và phát triển hạ tầng số, đảm bảo hệ thống thông tin liên lạc có tính sẵn sàng, an toàn và có độ dự phòng cao cho lực lượng CAND, nghiên cứu, ứng dụng và cung cấp các giải pháp số chất lượng cao cho tổ chức, người dân.'
  },
  commentsPack: {
    commentSectionName: 'Feedback',
    information: 'Information',
    articleComments: 'Article comments',
    name: 'Name',
    email: 'Email',
    comment: 'Comment',
    applicationInformation: 'Application information',
    fullname: 'Fullname',
    informationFile: 'Information file',
    total: 'Total',
    noData: 'No data',
    article: 'Article',
    detail: 'Detail',
    back: 'Back',
    applyFor: 'Apply for',
    telephone: 'Telephone',
    clickToViewDetails: 'Click to view details',
    clickToDeleteThisComment: 'Click to delete this comment',
    clickToApproveThisComment: 'Click to approve this comment',
    clickToRejectThisComment: 'Click to reject this comment',
    commenterInformation: "Commenter's information",
    status: "Status",
    delete: "Delete",
    deleteSelectedComments: "Delete the selected comments",
    yes: "Yes",
    no: "No",
    deleteComment: "Delete the comment",
    areYouSureDeleteThisComment: "Are you sure delete this comment?",
    areYouSureDeleteTheSelectedComments: "Are you sure delete the selected comments?",
    completedSuccessfully: "Completed successfully!",
    executionFailed: "Execution failed!",
    approved: "Approved",
    notApproved: "Not approved",
    approve: "Approve",
    notApprove: "Not approve",
    candidateInformation: "Candidate information",
    positionAvailable: "Position available",
    download: "Download",
    view: "View",
    noSuitableJobFound: "No suitable job found!",
    deleteCandidate: "Delete the candidate",
    deleteSelectedCandidates: "Delete the selected candidates",
    areYouSureDeleteThisCandidate: "Are you sure delete this candidate?",
    areYouSureDeleteTheSelectedCandidates: "Are you sure delete the selected candidates?",
  }
};
