export default {
  gtelPortal: {
    companyName: 'GTEL',
    companyFullname: 'Tổng công ty công nghệ - viễn thông toàn cầu',
    introDescription1: 'Cuộc cách mạng 4.0 mở ra kỷ nguyên số với sự chuyển đổi toàn diện về đời sống xã hội, mở ra nhiều cơ hội, song cũng đặt ra không ít thách thức đối với vấn đề an ninh truyền thống và phi truyền thống, Bộ Công an xác định để thực hiện thắng lợi nhiệm vụ xây dựng lực lượng Công an nhân dân chính quy – tinh nhuệ, hiện đại thì công nghiệp An ninh là một bộ phận quan trọng trong thực lực và tiềm lực của lực lượng CAND, vừa phục vụ công tác chiến đấu và xây dựng lực lượng vừa phục vụ phát triển kinh tế xã hội.',
    introDescription2: 'Là Tổng công ty duy nhất của ngành Công an có vai trò trực tiếp phục vụ quốc phòng – an ninh, tiên phong trong lĩnh vực công nghệ - viễn thông, GTEL đảm trách một sứ mệnh đặc biệt. Với sứ mệnh đó, GTEL luôn xác định nhiệm vụ trọng tâm là viễn thông, tự động hóa, đồng thời, dần chuyển mình sang nhiều lĩnh vực công nghệ cao, thực hiện Đề án 06 và Chương trình Chuyển đổi số Quốc gia của Chính phủ, hướng đến mục tiêu vừa phục vụ phát triển công nghiệp an ninh, công nghiệp an ninh mạng vừa phát triển kinh tế, đóng góp mạnh mẽ vào xây dựng lực lượng Công an, hòa mình vào nền công nghiệp hiện đại của quốc gia, trở thành doanh nghiệp có tầm ảnh hưởng quốc tế.',
    introBlock1_label: 'Tầm nhìn',
    introBlock1_content: 'Trở thành Tập đoàn Công nghệ - Viễn thông mạnh, hiện đại, tiên tiến trong nước và thế giới và là doanh nghiệp trực tiếp phục vụ quốc phòng, an ninh hàng đầu Bộ Công an, phục vụ đắc lực công tác chiến đấu và sẵn sàng chiến đấu của lực lượng CAND.',
    introBlock2_label: 'Sứ mệnh',
    introBlock2_content: 'Tiên phong trong việc kiến tạo xã hội số, xây dựng và phát triển hạ tầng số, đảm bảo hệ thống thông tin liên lạc có tính sẵn sàng, an toàn và có độ dự phòng cao cho lực lượng CAND, nghiên cứu, ứng dụng và cung cấp các giải pháp số chất lượng cao cho tổ chức, người dân.',
  },
  commentsPack: {
    commentSectionName: 'Thông tin phản hồi',
    information: 'Thông tin',
    articleComments: 'Nhận xét bài viết',
    name: 'Tên',
    email: 'Email',
    comment: 'Ý kiến',
    applicationInformation: 'Thông tin ứng tuyển',
    fullname: 'Họ tên',
    informationFile: 'Tệp thông tin',
    total: 'Tổng',
    noData: 'Không có dữ liệu',
    article: 'Bài viết',
    detail: 'Chi tiết',
    back: 'Quay lại',
    applyFor: 'Ứng tuyển cho',
    telephone: 'Điện thoại',
    clickToViewDetails: 'Bấm để xem chi tiết',
    clickToDeleteThisComment: 'Bấm để xóa ý kiến này',
    clickToApproveThisComment: 'Bấm để phê duyệt ý kiến này',
    clickToRejectThisComment: 'Bấm để hủy phê duyệt ý kiến này',
    commenterInformation: "Thông tin người đưa ý kiến",
    status: "Trạng thái",
    delete: "Xóa",
    deleteSelectedComments: "Xóa các ý kiến đã chọn",
    yes: "Có",
    no: "Không",
    deleteComment: "Xóa ý kiến",
    areYouSureDeleteThisComment: "Bạn có chắc chắn xóa ý kiến này không?",
    areYouSureDeleteTheSelectedComments: "Bạn có chắc chắn xóa các ý kiến đã chọn không?",
    completedSuccessfully: "Thực hiện thành công!",
    executionFailed: "Thực hiện không thành công!",
    approved: "Đã phê duyệt",
    notApproved: "Không phê duyệt",
    approve: "Phê duyệt",
    notApprove: "Không phê duyệt",
    candidateInformation: "Thông tin ứng viên",
    positionAvailable: "Ứng tuyển vị trí",
    download: "Tải xuống",
    view: "Xem",
    noSuitableJobFound: "Chưa tìm được việc phù hợp!",
    deleteCandidate: "Xóa ứng viên",
    deleteSelectedCandidates: "Xóa các ứng viên đã chọn",
    areYouSureDeleteThisCandidate: "Bạn có chắc chắn xóa ứng viên này không?",
    areYouSureDeleteTheSelectedCandidates: "Bạn có chắc chắn xóa các ứng viên đã chọn không?",
  }
};
