const CMS_SECTION_COMMENT_ALIAS = "Gtel.Portal.Section.Comment";
const CMS_SIDEBARMENU_COMMENT_ALIAS = "Gtel.Portal.SidebarMenu.Comment";
const CMS_MENU_COMMENT_ALIAS = "Gtel.Portal.Menu.Comment";
const CMS_MENUITEM_NEWSCOMMENT_ALIAS = "Gtel.Portal.MenuItem.NewsComment";
const CMS_MENUITEM_APPLICATIONINFORMATION_ALIAS = "Gtel.Portal.MenuItem.ApplicationInformation";
const CMS_ENTITY_TYPE_NEWSCOMMENT = "newscomment";
const CMS_WORKSPACE_NEWSCOMMENT_ALIAS = "Gtel.Portal.Workspace.NewsComment";
const CMS_WORKSPACE_CONTEXT_NEWSCOMMENT = "Gtel.Portal.WorkspaceContext.NewsComment";
const CMS_ENTITY_TYPE_APPLICATIONINFORMATION = "applicationinformation";
const CMS_WORKSPACE_APPLICATIONINFORMATION_ALIAS = "Gtel.Portal.Workspace.ApplicationInformation";
const CMS_WORKSPACE_CONTEXT_APPLICATIONINFORMATION = "Gtel.Portal.WorkspaceContext.ApplicationInformation";
export {
  CMS_ENTITY_TYPE_APPLICATIONINFORMATION,
  CMS_ENTITY_TYPE_NEWSCOMMENT,
  CMS_MENUITEM_APPLICATIONINFORMATION_ALIAS,
  CMS_MENUITEM_NEWSCOMMENT_ALIAS,
  CMS_MENU_COMMENT_ALIAS,
  CMS_SECTION_COMMENT_ALIAS,
  CMS_SIDEBARMENU_COMMENT_ALIAS,
  CMS_WORKSPACE_APPLICATIONINFORMATION_ALIAS,
  CMS_WORKSPACE_CONTEXT_APPLICATIONINFORMATION,
  CMS_WORKSPACE_CONTEXT_NEWSCOMMENT,
  CMS_WORKSPACE_NEWSCOMMENT_ALIAS
};
//# sourceMappingURL=constants.js.map
